<?php
/**
 * Windwalkers - Chapter tile grids (no filesystem access)
 *
 * BGA forbids using file_get_contents on the server. To avoid that,
 * we embed the chapter grid data directly as PHP arrays.
 * Only the keys required by setup (q, r, name) are included.
 */

$this->chapters = [
    1 => [
        'title' => 'Windwalker - Chapter 1',
        'start_city' => 'aberlaas',
        'end_city' => 'portchoon',
        'grid' => [
            ['q' => 3, 'r' => 17, 'name' => 'aberlaas'],
            ['q' => 3, 'r' => 16, 'name' => 'mountain'],
            ['q' => 3, 'r' => 14, 'name' => 'village_green'],
            ['q' => 1, 'r' => 16, 'name' => 'village_blue'],
            ['q' => 5, 'r' => 12, 'name' => 'village_red'],
            ['q' => 2, 'r' => 17, 'name' => 'plain'],
            ['q' => 1, 'r' => 17, 'name' => 'plain'],
            ['q' => 4, 'r' => 15, 'name' => 'plain'],
            ['q' => 5, 'r' => 14, 'name' => 'plain'],
            ['q' => 5, 'r' => 13, 'name' => 'plain'],
            ['q' => 4, 'r' => 12, 'name' => 'plain'],
            ['q' => 1, 'r' => 15, 'name' => 'plain'],
            ['q' => 2, 'r' => 13, 'name' => 'plain'],
            ['q' => 3, 'r' => 12, 'name' => 'hut'],
            ['q' => 1, 'r' => 14, 'name' => 'hut'],
            ['q' => 2, 'r' => 15, 'name' => 'hut'],
            ['q' => 5, 'r' => 15, 'name' => 'hut'],
            ['q' => 2, 'r' => 16, 'name' => 'mountain'],
            ['q' => 2, 'r' => 14, 'name' => 'mountain'],
            ['q' => 3, 'r' => 13, 'name' => 'mountain'],
            ['q' => 4, 'r' => 13, 'name' => 'forest'],
            ['q' => 4, 'r' => 14, 'name' => 'forest'],
            ['q' => 3, 'r' => 15, 'name' => 'forest'],
            ['q' => 4, 'r' => 16, 'name' => 'forest'],
            ['q' => 3, 'r' => 11, 'name' => 'portchoon'],
        ],
    ],
    2 => [
        'title' => 'Windwalker - Chapter 2',
        'start_city' => 'portchoon',
        'end_city' => 'chawondasee',
        'grid' => [
            ['q' => 3, 'r' => 4, 'name' => 'portchoon'],
            ['q' => 3, 'r' => 2, 'name' => 'tourfontaine'],
            ['q' => 3, 'r' => 1, 'name' => 'water'],
            ['q' => 3, 'r' => 3, 'name' => 'water'],
            ['q' => 4, 'r' => 2, 'name' => 'water'],
            ['q' => 4, 'r' => 1, 'name' => 'water'],
            ['q' => 5, 'r' => 2, 'name' => 'water'],
            ['q' => 6, 'r' => 1, 'name' => 'water'],
            ['q' => 6, 'r' => 0, 'name' => 'water'],
            ['q' => 5, 'r' => 0, 'name' => 'water'],
            ['q' => 5, 'r' => 1, 'name' => 'village_green'],
            ['q' => 3, 'r' => 0, 'name' => 'chawondasee'],
            ['q' => 7, 'r' => 1, 'name' => 'village_red'],
            ['q' => 6, 'r' => -1, 'name' => 'village_blue'],
            ['q' => 4, 'r' => 0, 'name' => 'hut'],
            ['q' => 6, 'r' => 2, 'name' => 'hut'],
            ['q' => 5, 'r' => -1, 'name' => 'forest'],
            ['q' => 4, 'r' => 3, 'name' => 'forest'],
            ['q' => 5, 'r' => 3, 'name' => 'mountain'],
            ['q' => 7, 'r' => 0, 'name' => 'mountain'],
            ['q' => 7, 'r' => -1, 'name' => 'plain'],
        ],
    ],
    3 => [
        'title' => 'Windwalker - Chapter 3',
        'start_city' => 'chawondasee',
        'end_city' => 'alticcio',
        'grid' => [
            ['q' => 6, 'r' => 7, 'name' => 'chawondasee'],
            ['q' => 5, 'r' => 7, 'name' => 'desert'],
            ['q' => 4, 'r' => 7, 'name' => 'desert'],
            ['q' => 3, 'r' => 7, 'name' => 'desert'],
            ['q' => 2, 'r' => 7, 'name' => 'desert'],
            ['q' => 1, 'r' => 7, 'name' => 'alticcio'],
            ['q' => 2, 'r' => 6, 'name' => 'hut'],
            ['q' => 3, 'r' => 6, 'name' => 'desert'],
            ['q' => 4, 'r' => 5, 'name' => 'desert'],
            ['q' => 4, 'r' => 8, 'name' => 'desert'],
            ['q' => 3, 'r' => 9, 'name' => 'desert'],
            ['q' => 2, 'r' => 9, 'name' => 'plain'],
            ['q' => 1, 'r' => 8, 'name' => 'mountain'],
            ['q' => 1, 'r' => 9, 'name' => 'mountain'],
            ['q' => 3, 'r' => 5, 'name' => 'mountain'],
            ['q' => 5, 'r' => 6, 'name' => 'plain'],
            ['q' => 6, 'r' => 6, 'name' => 'forest'],
            ['q' => 5, 'r' => 8, 'name' => 'plain'],
            ['q' => 3, 'r' => 8, 'name' => 'village_red'],
            ['q' => 4, 'r' => 6, 'name' => 'village_blue'],
            ['q' => 4, 'r' => 9, 'name' => 'hut'],
            ['q' => 5, 'r' => 5, 'name' => 'hut'],
            ['q' => 2, 'r' => 8, 'name' => 'plain'],
            ['q' => 6, 'r' => 5, 'name' => 'forest'],
            ['q' => 1, 'r' => 10, 'name' => 'village_green'],
        ],
    ],
    4 => [
        'title' => 'Windwalker - Chapter 4',
        'start_city' => 'alticcio',
        'end_city' => 'campboban',
        'grid' => [
            ['q' => 10, 'r' => 38, 'name' => 'alticcio'],
            ['q' => 9, 'r' => 38, 'name' => 'portedhurle'],
            ['q' => 8, 'r' => 39, 'name' => 'mountain'],
            ['q' => 9, 'r' => 37, 'name' => 'mountain'],
            ['q' => 10, 'r' => 36, 'name' => 'mountain'],
            ['q' => 7, 'r' => 39, 'name' => 'swamp'],
            ['q' => 8, 'r' => 38, 'name' => 'swamp'],
            ['q' => 8, 'r' => 37, 'name' => 'swamp'],
            ['q' => 7, 'r' => 37, 'name' => 'swamp'],
            ['q' => 6, 'r' => 38, 'name' => 'swamp'],
            ['q' => 7, 'r' => 36, 'name' => 'swamp'],
            ['q' => 9, 'r' => 36, 'name' => 'swamp'],
            ['q' => 8, 'r' => 36, 'name' => 'forest'],
            ['q' => 6, 'r' => 39, 'name' => 'plain'],
            ['q' => 6, 'r' => 37, 'name' => 'plain'],
            ['q' => 10, 'r' => 35, 'name' => 'hut'],
            ['q' => 5, 'r' => 38, 'name' => 'village_green'],
            ['q' => 6, 'r' => 36, 'name' => 'swamp'],
            ['q' => 6, 'r' => 35, 'name' => 'campboban'],
            ['q' => 8, 'r' => 35, 'name' => 'hut'],
            ['q' => 7, 'r' => 40, 'name' => 'mountain'],
        ],
    ],
];
