<?php
/**
 * Windwalkers - Characters (Hordiers)
 * Generated from horde_cards.xlsx
 */

$this->characters = [
    1 => [
        'name' => clienttranslate('Uther le Fonceur'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate(':tap:: :discard: pour ignorer -3 :d6-black-white-green: / :missing:'),
        'power_type' => 'discard',
        'power_code' => 'uther_power',
    ],
    2 => [
        'name' => clienttranslate('Rokka le Cerf-Volant'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate(':tap:: Placez 1 :force-x: Ignorez :d6-black-white-green: dont la valeur est > à ce :force-x:'),
        'power_type' => 'tap',
        'power_code' => 'rokka_power',
    ],
    3 => [
        'name' => clienttranslate('Alpha l\'Econome'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 1,
        'power' => clienttranslate('∞: Placez 0+ :d6-blue-violet: sur <b>Alpha</b>. Ils sont ignorés. \n:tap:: Utilisez :d6-blue-violet: tels quels.'),
        'power_type' => 'tap',
        'power_code' => 'alpha_power',
    ],
    4 => [
        'name' => clienttranslate('Ryage le Joueur'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate(':tap:: Perdez -1 :moral: et lancez 1 :d6-blue:.\nSi :d6-blue: ≥ à :force-x:, ignorez tous :d6-black-white-green:'),
        'power_type' => 'tap',
        'power_code' => 'ryage_power',
    ],
    5 => [
        'name' => clienttranslate('Viciar le Perfectionniste'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate(':tap:: Ignorez -1 :d6-black-white-green: / :d6-green:'),
        'power_type' => 'tap',
        'power_code' => 'viciar_power',
    ],
    6 => [
        'name' => clienttranslate('Thomassin de Gaude'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Faites ±1 sur la valeur de chacun de :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'thomassin_power',
    ],
    7 => [
        'name' => clienttranslate('Ukkiba Tomoshi'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Perdez -1 :moral:. Faites ±1 / :moral: restant sur :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'ukkiba_power',
    ],
    8 => [
        'name' => clienttranslate('Filibert Franz'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Ignorez les pénalités de :moral: liées au terrain.'),
        'power_type' => 'tap',
        'power_code' => 'filibert_power',
    ],
    9 => [
        'name' => clienttranslate('Herbert Benegh'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Retirez une :tuile: grise du plateau. Si <b>FRANCK</b> n\'est pas dans votre équipe, perdez -1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'herbert_power',
    ],
    10 => [
        'name' => clienttranslate('Franck Benegh'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Échangez 2 :tuile: grises et adjacentes à la vôtre. Si <b>HERBERT</b> n\'est pas dans votre équipe, perdez -1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'franck_power',
    ],
    11 => [
        'name' => clienttranslate('Athonios Catan'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Annulez toutes vos actions, reculez et rejouez immédiatement.'),
        'power_type' => 'tap',
        'power_code' => 'athonios_power',
    ],
    12 => [
        'name' => clienttranslate('Blanchette de Gaude'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Faites ±1 sur :d6-blue: / :force-x:'),
        'power_type' => 'tap',
        'power_code' => 'blanchette_power',
    ],
    13 => [
        'name' => clienttranslate('Ed Abro Ragerage'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Posez tous :d6-green: sur <b>Ed</b>. Ils sont ignorés et seront ajoutés au prochain contre.\n:rest:: <b>Ed</b>, retirez ces :d6-green:'),
        'power_type' => 'tap',
        'power_code' => 'ed_power',
    ],
    14 => [
        'name' => clienttranslate('Kunigunde Nosske'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Si la somme :d6-blue: est > :d6-white-green:, ignorez tous :d6-white:'),
        'power_type' => 'tap',
        'power_code' => 'kunigunde_power',
    ],
    15 => [
        'name' => clienttranslate('Anika'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue: / :force-x: = :force-x:'),
        'power_type' => 'tap',
        'power_code' => 'anika_power',
    ],
    16 => [
        'name' => clienttranslate('Kon'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Relancez tout ou partie de :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'kon_power',
    ],
    17 => [
        'name' => clienttranslate('Waldo Waldmann'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Ignorez -1 :d6-green: / :missing:'),
        'power_type' => 'tap',
        'power_code' => 'waldo_power',
    ],
    18 => [
        'name' => clienttranslate('Dorothy Irony'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Faites ±1 / <b>OISELEUR</b> sur 1 :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'dorothy_power',
    ],
    19 => [
        'name' => clienttranslate('Oshora'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Gagnez +1 :moral: / :missing:.\nSi vous :discard: <b>Zhalinka</b>, :discard: <b>Oshora</b> aussi puis activez son pouvoir'),
        'power_type' => 'discard',
        'power_code' => 'oshora_power',
    ],
    20 => [
        'name' => clienttranslate('Adolar Rossel'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: :discard: 1 :card: <b>FER/PACK/TRAÎNE</b>.\nRecrutez votre <b>Faucon</b>.'),
        'power_type' => 'discard',
        'power_code' => 'adolar_power',
    ],
    21 => [
        'name' => clienttranslate('Alicone Minh-row'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Retirez -1 à :force-x: \nOU \najoutez +1 à :force-x: et gagnez +2 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'alicone_power',
    ],
    22 => [
        'name' => clienttranslate('Ashley'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: :rest-all:. Perdez -1 :moral: / :rest:'),
        'power_type' => 'tap',
        'power_code' => 'ashley_power',
    ],
    23 => [
        'name' => clienttranslate('Baramas'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Si :force-x: = <b>CHOON</b> :force-3:, gagnez +3 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'baramas_power',
    ],
    24 => [
        'name' => clienttranslate('Xavio Torantor'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue:.\nSi vous avez un autre <b>TORANTOR</b>, \nFaites ±1 sur 1 :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'xavio_power',
    ],
    25 => [
        'name' => clienttranslate('Yavo Torantor'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue:. \nSi vous avez 1 autre <b>TORANTOR</b>, \nGagnez +1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'yavo_power',
    ],
    26 => [
        'name' => clienttranslate('Ernest Waltman'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Placez 1 :force-x: sur 3 :tuile: adjacentes.'),
        'power_type' => 'tap',
        'power_code' => 'ernest_power',
    ],
    27 => [
        'name' => clienttranslate('Galas Thunderflayer'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Si :force-x: = <b>FUREVENT</b> :force-6:, :rest-all:'),
        'power_type' => 'tap',
        'power_code' => 'galas_power',
    ],
    28 => [
        'name' => clienttranslate('Gianni Raymondi'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Placez 1 :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'gianni_power',
    ],
    29 => [
        'name' => clienttranslate('Ivan Baumann'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue-violet: / :card: <b>FER</b>.'),
        'power_type' => 'tap',
        'power_code' => 'ivan_power',
    ],
    30 => [
        'name' => clienttranslate('Lethune de Prals'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue: / :moral: sur :tuile:'),
        'power_type' => 'tap',
        'power_code' => 'lethune_power',
    ],
    31 => [
        'name' => clienttranslate('Osvaldo Hawksson'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Si :tuile: = 3 :d6-green:, gagnez +3 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'osvaldo_power',
    ],
    32 => [
        'name' => clienttranslate('Rochelle Niephaus'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: :force-x: ⮕ :force-1: Perdez -1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'rochelle_power',
    ],
    33 => [
        'name' => clienttranslate('Saskia Bisch'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Si :tuile: = 2 :d6-green:, gagnez +2 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'saskia_power',
    ],
    34 => [
        'name' => clienttranslate('Vera'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: :rest:'),
        'power_type' => 'tap',
        'power_code' => 'vera_power',
    ],
    35 => [
        'name' => clienttranslate('Wanda Pfeffer'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Ignorez -1 :d6-white-green:'),
        'power_type' => 'tap',
        'power_code' => 'wanda_power',
    ],
    36 => [
        'name' => clienttranslate('Emelyn Kraw'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Faites ±1 sur 1 :d6-blue: / :card: <b>PACK</b>.'),
        'power_type' => 'tap',
        'power_code' => 'emelyn_power',
    ],
    37 => [
        'name' => clienttranslate('Faucon'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Si vous avez 1 :card: <b>OISELEUR</b>.\nRecrutez +1 :discard:'),
        'power_type' => 'discard',
        'power_code' => 'faucon_power',
    ],
    38 => [
        'name' => clienttranslate('Croque'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Recrutez 1 :discard:'),
        'power_type' => 'discard',
        'power_code' => 'croque_power',
    ],
    39 => [
        'name' => clienttranslate('Abriyen'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: :rest: :rest:'),
        'power_type' => 'discard',
        'power_code' => 'abriyen_power',
    ],
    40 => [
        'name' => clienttranslate('Yeng'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Échangez 2 :tuile: grises et adjacentes.'),
        'power_type' => 'discard',
        'power_code' => 'yeng_power',
    ],
    41 => [
        'name' => clienttranslate('Belkacem'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Placez 1 :d6-green:'),
        'power_type' => 'tap',
        'power_code' => 'belkacem_power',
    ],
    42 => [
        'name' => clienttranslate('Benelim'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Lancez +1 :d6-blue-violet: / :card: <b>PACK</b>.'),
        'power_type' => 'discard',
        'power_code' => 'benelim_power',
    ],
    43 => [
        'name' => clienttranslate('Duke Arnaud N.'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Placez 2 :d6-blue-violet:'),
        'power_type' => 'discard',
        'power_code' => 'duke_power',
    ],
    44 => [
        'name' => clienttranslate('Tula'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: :force-x: ⮕ :force-2:'),
        'power_type' => 'discard',
        'power_code' => 'tula_power',
    ],
    45 => [
        'name' => clienttranslate('Comtesse Elewys'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Ignorez -2 :d6-black-white-green:'),
        'power_type' => 'discard',
        'power_code' => 'comtesse_power',
    ],
    46 => [
        'name' => clienttranslate('Amiral Jean'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Chaque :moral: dépensé compte double.'),
        'power_type' => 'discard',
        'power_code' => 'amiral_power',
    ],
    47 => [
        'name' => clienttranslate('Topilzin'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: :force-x: ⮕ :force-3:'),
        'power_type' => 'discard',
        'power_code' => 'topilzin_power',
    ],
    48 => [
        'name' => clienttranslate('Zhalinka'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Lancez +1 :d6-blue-violet: / :missing:'),
        'power_type' => 'discard',
        'power_code' => 'zhalinka_power',
    ],
    49 => [
        'name' => clienttranslate('Bellune'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Placez 1 :d6-blue-violet: / :missing:'),
        'power_type' => 'discard',
        'power_code' => 'bellune_power',
    ],
    50 => [
        'name' => clienttranslate('Osuros'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: :force-x: ⮕ :force-6:'),
        'power_type' => 'discard',
        'power_code' => 'osuros_power',
    ],
    51 => [
        'name' => clienttranslate('Mère'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Gagnez +3 :moral:\nSi :discard: <b>Père</b> le même tour, regagnez tout :moral:'),
        'power_type' => 'discard',
        'power_code' => 'mère_power',
    ],
    52 => [
        'name' => clienttranslate('Père'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Gagnez +3 :moral:\nSi :discard: <b>Mère</b> le même tour, regagnez tout :moral:'),
        'power_type' => 'discard',
        'power_code' => 'père_power',
    ],
    53 => [
        'name' => clienttranslate('Fuego'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Placez 1 :force-x: sur chaque :tuile: adjacente'),
        'power_type' => 'discard',
        'power_code' => 'fuego_power',
    ],
    54 => [
        'name' => clienttranslate('Ama Ama'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Faites ±1 sur :d6-blue-violet: / :moral:'),
        'power_type' => 'discard',
        'power_code' => 'ama_power',
    ],
    55 => [
        'name' => clienttranslate('Giltarr le Tricheur'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate(':tap:: Si vous rejoingnez une <b>Horde</b>, ignorez tous les :d6-black-white-green:'),
        'power_type' => 'tap',
        'power_code' => 'giltarr_power',
        'extension' => '2-players',
    ],
    56 => [
        'name' => clienttranslate('Usmos l\'Eunuque'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate(':tap:: Utilisez un pouvoir :card: <b>TRAÎNE</b> sans :discard:.\n:tap: ce :card:<b>TRAÎNE</b>'),
        'power_type' => 'discard',
        'power_code' => 'usmos_power',
    ],
    57 => [
        'name' => clienttranslate('Estrella l\'Innebranlable'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate(':tap:: Distribuez équitablement vos :d6-black: sur les :tuile: adjacentes, ces :d6-black: modifient définitivement la :tuile: puis :d6-violet: = :d6-blue:'),
        'power_type' => 'tap',
        'power_code' => 'estrella_power',
    ],
    58 => [
        'name' => clienttranslate('I.E.L'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate(':tap:: Si :tuile: manquante autour de votre :tuile:, ignorez -3 :d6-black-white-green:'),
        'power_type' => 'tap',
        'power_code' => 'iel_power',
    ],
    59 => [
        'name' => clienttranslate('Ambroise le Coquin'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate(':tap:: Retournez un :card: (n\'importe lequel, n\'importe où) si :rest: un :card: adverse, gagnez +3 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'ambroise_power',
        'extension' => '2-players',
    ],
    60 => [
        'name' => clienttranslate('Oranne la Voyageuse'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 1,
        'power' => clienttranslate(':tap:: Si :tuile: avec :moral: alors ignorez -3 :d6-black-white-green:'),
        'power_type' => 'tap',
        'power_code' => 'oranne_power',
    ],
    61 => [
        'name' => clienttranslate('Lyara l\'Inspirante'),
        'type' => CHAR_TRACEUR,
        'position' => 'traceur',
        'is_leader' => true,
        'tier' => 1,
        'power' => clienttranslate(':tap:: :tuile: villages = :tuile: villes: Ignorez tous :d6-black-white-green: et vous recrutez tout type de :card: Si :rest-all: gagnez  +1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'lyara_power',
    ],
    62 => [
        'name' => clienttranslate('Maarveen Guillor'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Définissez une valeur et mettez tous :d6-blue: sur cette valeur.'),
        'power_type' => 'tap',
        'power_code' => 'maarveen_power',
    ],
    63 => [
        'name' => clienttranslate('Arabine'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Ignorez les :d6-white: < à votre :d6-blue: le plus faible.'),
        'power_type' => 'tap',
        'power_code' => 'arabine_power',
    ],
    64 => [
        'name' => clienttranslate('Thutmus'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Lancez autant :d6-blue: / Force :force-x:, ni plus, ni moins.'),
        'power_type' => 'tap',
        'power_code' => 'thutmus_power',
    ],
    65 => [
        'name' => clienttranslate('Dunseth Calsan'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: :discard: 1 :card: <b>FER</b>\nRecrutez 1 :card: <b>Calsan</b> et :rest-all: <b>Calsans</b>.'),
        'power_type' => 'discard',
        'power_code' => 'dunseth_power',
    ],
    66 => [
        'name' => clienttranslate('Irilad Calsan'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: :discard: 1 :card: <b>TRAÎNE</b>. \nPlacez :d6-blue: / :missing: <b>TRAÎNE</b>.'),
        'power_type' => 'discard',
        'power_code' => 'irilad_power',
    ],
    67 => [
        'name' => clienttranslate('Oravan Calsan'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: :discard: 1 :card: <b>PACK</b>. \nLancez +1 :d6-blue: / :missing: <b>PACK</b>.'),
        'power_type' => 'discard',
        'power_code' => 'oravan_power',
    ],
    68 => [
        'name' => clienttranslate('Justin Rubino'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Ignorez :d6-green: / :card: <b>FEULEUR</b>'),
        'power_type' => 'tap',
        'power_code' => 'justin_power',
    ],
    69 => [
        'name' => clienttranslate('Amon Amon'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Ignorez :d6-white: / :d6-black:'),
        'power_type' => 'tap',
        'power_code' => 'amon_power',
    ],
    70 => [
        'name' => clienttranslate('Jared Smeth'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue: / :card: <b>OISELEUR</b>.'),
        'power_type' => 'tap',
        'power_code' => 'jared_power',
    ],
    71 => [
        'name' => clienttranslate('Cassandre'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Ignorez tous :d6-white-green: et donnez <b>Cassandre</b> à votre voisin de gauche. \nCette <b>Horde</b> :discard: <b>FER</b>'),
        'power_type' => 'discard',
        'power_code' => 'cassandre_power',
        'extension' => '2-players',
    ],
    72 => [
        'name' => clienttranslate('Ragnard Telsen'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Rajoutez +1 :d6-black: / :card: <b>géomaître</b> sur une :tuile: adjacente ou sur la vôtre. Ces :d6-black: modifient définitivement la :tuile:'),
        'power_type' => 'tap',
        'power_code' => 'ragnard_power',
        'extension' => '2-players',
    ],
    73 => [
        'name' => clienttranslate('Lorwin Grenwald'),
        'type' => CHAR_FER,
        'position' => 'fer',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Prenez 1 :d6-blue: à une <b>Horde</b> devant vous. Si elle échoue son contre, perdez -1 :moral: Gagnez +1 :moral: sinon.'),
        'power_type' => 'tap',
        'power_code' => 'lorwin_power',
        'extension' => '2-players',
    ],
    74 => [
        'name' => clienttranslate('Josmina'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: :rest: / :d6-black:'),
        'power_type' => 'tap',
        'power_code' => 'josmina_power',
    ],
    75 => [
        'name' => clienttranslate('Nadia Ingot'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Remettez un vent du plateau dans la pioche. Piochez un autre vent si c\'est le vôtre.'),
        'power_type' => 'tap',
        'power_code' => 'nadia_power',
    ],
    76 => [
        'name' => clienttranslate('Eyline Bisch'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Gagnez +1 :moral: / :d6-black:'),
        'power_type' => 'tap',
        'power_code' => 'eyline_power',
    ],
    77 => [
        'name' => clienttranslate('Donmaer'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Ajoutez et placez jusqu\'à 2 :d6-green:'),
        'power_type' => 'tap',
        'power_code' => 'donmaer_power',
    ],
    78 => [
        'name' => clienttranslate('Kyo Torantor'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Lancez +1 :d6-blue: Si vous avez 1 autre :card: <b>Torantor</b>, :rest: cette :card:.'),
        'power_type' => 'tap',
        'power_code' => 'kyo_power',
    ],
    79 => [
        'name' => clienttranslate('Bert Haring'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Donnez -1 :d6-green: à une <b>Horde</b> adjacente. Si elle échoue son contre, perdez -1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'bert_power',
        'extension' => '2-players',
    ],
    80 => [
        'name' => clienttranslate('Sarbella'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Ne perdez pas de :moral: en utilisant vos alliés OU gagnez +1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'sarbella_power',
    ],
    81 => [
        'name' => clienttranslate('Le Daron'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Lancez 1 :d6-blue: : \n1-2 : Perdez -1 :moral: \n3-5 : Gagnez +2 :moral: \n6 : Toutes les <b>Hordes</b> gagnent +2 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'le_power',
    ],
    82 => [
        'name' => clienttranslate('Le Dragon'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: :tap: 1 autre :card: et gagnez +4 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'le_power',
    ],
    83 => [
        'name' => clienttranslate('Sylvana Delcourt'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Tous les :d6-green: ignorés sont donnés à la <b>Horde</b> suivante.'),
        'power_type' => 'tap',
        'power_code' => 'sylvana_power',
        'extension' => '2-players',
    ],
    84 => [
        'name' => clienttranslate('Saphira Montclair'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Donnez -1 :d6-blue: à une <b>Horde</b> adjacente. :rest: en contrepartie.'),
        'power_type' => 'tap',
        'power_code' => 'saphira_power',
        'extension' => '2-players',
    ],
    85 => [
        'name' => clienttranslate('Darius Voren'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Équilibrez le :moral: des <b>Hordes</b> adjacentes et le vôtre.'),
        'power_type' => 'tap',
        'power_code' => 'darius_power',
        'extension' => '2-players',
    ],
    86 => [
        'name' => clienttranslate('Céleste Daramond'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 3,
        'power' => clienttranslate(':tap:: Échangez 1 :card: avec celui d’une autre <b>Horde</b> sur votre :tuile:(sauf le <b>Traceur</b>). Les deux <b>Hordes</b> regagnent 1 :moral:'),
        'power_type' => 'tap',
        'power_code' => 'céleste_power',
        'extension' => '2-players',
    ],
    87 => [
        'name' => clienttranslate('Alric Vorn'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Annulez le pouvoir d\'un :card: dirigé contre votre <b>Horde</b>.'),
        'power_type' => 'tap',
        'power_code' => 'alric_power',
        'extension' => '2-players',
    ],
    88 => [
        'name' => clienttranslate('Cassia Montclair'),
        'type' => CHAR_PACK,
        'position' => 'pack',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Déplacez une <b>Horde</b> adjacente sur votre :tuile: Regagnez +3 :moral: si elle avance.'),
        'power_type' => 'tap',
        'power_code' => 'cassia_power',
        'extension' => '2-players',
    ],
    89 => [
        'name' => clienttranslate('Sensemune'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Placez 1 de vos :card: <b>FER</b> sur ce :card: Il compte comme <b>FER</b> et <b>TRAÎNE</b>.'),
        'power_type' => 'tap',
        'power_code' => 'sensemune_power',
    ],
    90 => [
        'name' => clienttranslate('Sensesune'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':tap:: Placez 1 de vos :card:  <b>PACK</b> sur ce :card: Il compte comme <b>PACK</b> et <b>TRAÎNE</b>.'),
        'power_type' => 'tap',
        'power_code' => 'sensesune_power',
    ],
    91 => [
        'name' => clienttranslate('Régitha'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':tap:: Ignorez TOUS :d6-black-white-green: Une fois utilisée, <b>Régitha</b> ne peut être :discard:, remplacée ou :rest:'),
        'power_type' => 'discard',
        'power_code' => 'régitha_power',
    ],
    92 => [
        'name' => clienttranslate('Barakiel'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Tous les :d6-black: sont :d6-green: et les :d6-violet: sont :d6-blue:\n:force-x: ⮕ :force-1:'),
        'power_type' => 'discard',
        'power_code' => 'barakiel_power',
    ],
    93 => [
        'name' => clienttranslate('Charlize Soulages'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Gagnez +2 :moral: / :d6-black:'),
        'power_type' => 'discard',
        'power_code' => 'charlize_power',
    ],
    94 => [
        'name' => clienttranslate('Minerva'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Recrutez 1 :card: dans n\'importe quel village.'),
        'power_type' => 'discard',
        'power_code' => 'minerva_power',
    ],
    95 => [
        'name' => clienttranslate('Dr. Ana Pride'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Dévoilez +1 :card: / :tuile: village.'),
        'power_type' => 'discard',
        'power_code' => 'dr_power',
    ],
    96 => [
        'name' => clienttranslate('Ivana'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Ignorez :d6-black-white-green: < à :force-x:'),
        'power_type' => 'discard',
        'power_code' => 'ivana_power',
    ],
    97 => [
        'name' => clienttranslate('Hulan'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate('Placez 1 :d6-blue-violet: / :card: <b>OISELEUR</b> puis :discard: <b>Hulan</b>.'),
        'power_type' => 'discard',
        'power_code' => 'hulan_power',
    ],
    98 => [
        'name' => clienttranslate('Zaffa Torantor'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Lancez +1 :d6-violet:, :rest: 1 autre :card: <b>Torantor</b>.'),
        'power_type' => 'discard',
        'power_code' => 'zaffa_power',
    ],
    99 => [
        'name' => clienttranslate('Eolia Luthan'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Choisissez un autre Horde. Il doit perdre -2 :moral: ou relancer le :d6-blue: que vous désignez. S\'il réussit son contre, regagnez +3 :moral:'),
        'power_type' => 'discard',
        'power_code' => 'eolia_power',
        'extension' => '2-players',
    ],
    100 => [
        'name' => clienttranslate('Torren Varnay'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Augmentez la force d\'un vent adjacent.'),
        'power_type' => 'discard',
        'power_code' => 'torren_power',
    ],
    101 => [
        'name' => clienttranslate('Unicorn'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Lancez 1 :d6-blue: : \n1 : <b>Unicorn</b> vous tire la langue et votre <b>Horde</b> perd la partie. \n2-5: <b>Unicorn</b> fulmine et la partie continue. \n6 : <b>Unicorn</b> est ravie, votre <b>Horde</b> remporte la partie.'),
        'power_type' => 'discard',
        'power_code' => 'unicorn_power',
        'extension' => '2-players',
    ],
    102 => [
        'name' => clienttranslate('Lihn'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Doublez les points gagnés de ce tour.'),
        'power_type' => 'discard',
        'power_code' => 'lihn_power',
    ],
    103 => [
        'name' => clienttranslate('Tala Warai'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Remplacez une :tuile: grise par une autre :tuile: grise de la réserve. Le vent reste à sa place.'),
        'power_type' => 'discard',
        'power_code' => 'tala_power',
    ],
    104 => [
        'name' => clienttranslate('Jonas'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 3,
        'power' => clienttranslate(':discard:: Choisissez le vent dans la pioche (le vôtre ou celui de l\'adversaire).'),
        'power_type' => 'discard',
        'power_code' => 'jonas_power',
        'extension' => '2-players',
    ],
    105 => [
        'name' => clienttranslate('Selena Vane'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Échangez votre position avec celle d\'une Horde adjacent. Activez les bonus et/ou malus pour chacun.'),
        'power_type' => 'discard',
        'power_code' => 'selena_power',
        'extension' => '2-players',
    ],
    106 => [
        'name' => clienttranslate('Eryk Thorne'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Forcer une Horde adjacente à changer un :card: avec 1 :card: aléatoire de la pioche.'),
        'power_type' => 'discard',
        'power_code' => 'eryk_power',
        'extension' => '2-players',
    ],
    107 => [
        'name' => clienttranslate('Lorien Daramond'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Forcer une Horde à jouer 1 :card: que vous désignez s\'il est sur votre :tuile:'),
        'power_type' => 'discard',
        'power_code' => 'lorien_power',
        'extension' => '2-players',
    ],
    108 => [
        'name' => clienttranslate('Erynn Luthan'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 1,
        'power' => clienttranslate(':discard:: Annulez le pouvoir de 1 :card:'),
        'power_type' => 'discard',
        'power_code' => 'erynn_power',
        'extension' => '2-players',
    ],
    109 => [
        'name' => clienttranslate('Trump\'ette'),
        'type' => CHAR_TRAINE,
        'position' => 'traine',
        'tier' => 2,
        'power' => clienttranslate(':discard:: Changez une règle du jeu.'),
        'power_type' => 'discard',
        'power_code' => 'trumpette_power',
        'extension' => '2-players',
    ],
];
