<?php
/**
 * Windwalkers - Characters (Hordiers)
 * Each character has:
 * - id: unique identifier
 * - name: display name
 * - type: traceur, fer, pack, traine
 * - tier: power tier (1=best, 3=situational)
 * - power: description of the power
 * - power_code: internal code for power implementation
 */

$this->characters = [
    // ============ TRACEURS ============
    1 => [
        'name' => clienttranslate('Uther'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 1,
        'power' => clienttranslate('Abandonnez un hordier. Avancez automatiquement sur la prochaine tuile.'),
        'power_code' => 'abandon_advance',
    ],
    2 => [
        'name' => clienttranslate('Rokka'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Modifiez la force du vent de +1 ou -1.'),
        'power_code' => 'wind_control',
    ],
    3 => [
        'name' => clienttranslate('Ryage le Joueur'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate('Lancez 1 dé. Si sa valeur est >= à la force du vent, ignorez tous les dés du vent.'),
        'power_code' => 'gamble_wind',
    ],
    4 => [
        'name' => clienttranslate('Oranne'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Ignorez les dés verts de terrain.'),
        'power_code' => 'ignore_terrain',
    ],
    5 => [
        'name' => clienttranslate('Viciar'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Placez 2 de vos dés bleus sur la face de votre choix.'),
        'power_code' => 'set_two_dice',
    ],
    6 => [
        'name' => clienttranslate('Alpha'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Conservez un dé bleu pour le prochain lancer.'),
        'power_code' => 'save_die',
    ],
    7 => [
        'name' => clienttranslate('Usmos'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Les Traînes peuvent utiliser leur pouvoir sans être abandonnés.'),
        'power_code' => 'traine_safe',
    ],
    8 => [
        'name' => clienttranslate('Estrella'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate('Modifiez un dé noir de +1 ou -1.'),
        'power_code' => 'black_dice_control',
    ],
    9 => [
        'name' => clienttranslate('Lyara'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Posez un village sur une tuile adjacente vide.'),
        'power_code' => 'place_village',
    ],
    10 => [
        'name' => clienttranslate('I.E.L'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Déplacez-vous sur une tuile de bordure adjacente sans affronter le vent.'),
        'power_code' => 'border_move',
    ],
    11 => [
        'name' => clienttranslate('Giltarr'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 3,
        'power' => clienttranslate('Déplacez votre horde sur la tuile d\'un autre joueur.'),
        'power_code' => 'teleport_player',
    ],
    12 => [
        'name' => clienttranslate('Ambroise'),
        'type' => CHAR_TRACEUR,
        'is_leader' => true,
        'tier' => 2,
        'power' => clienttranslate('Restaurez le pouvoir d\'un hordier déjà utilisé.'),
        'power_code' => 'restore_power',
    ],

    // ============ FERS ============
    20 => [
        'name' => clienttranslate('Blanchette de Gaude'),
        'type' => CHAR_FER,
        'tier' => 3,
        'power' => clienttranslate('Faites ±1 sur vos dés bleus autant de fois que la force du vent.'),
        'power_code' => 'modify_by_wind',
    ],
    21 => [
        'name' => clienttranslate('Waldo'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Si un hordier est abandonné ce tour, +2 à tous vos dés.'),
        'power_code' => 'abandon_bonus',
    ],
    22 => [
        'name' => clienttranslate('Thomassin'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Faites ±1 sur chacun de vos dés bleus.'),
        'power_code' => 'modify_all_dice',
    ],
    23 => [
        'name' => clienttranslate('Anika'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Ignorez 2 dés blancs du vent.'),
        'power_code' => 'ignore_two_wind',
    ],
    24 => [
        'name' => clienttranslate('Ukkiba'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Échangez un dé bleu avec un dé blanc.'),
        'power_code' => 'swap_dice',
    ],
    25 => [
        'name' => clienttranslate('Kon'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Relancez jusqu\'à 3 dés bleus.'),
        'power_code' => 'reroll_three',
    ],
    26 => [
        'name' => clienttranslate('Athonios'),
        'type' => CHAR_FER,
        'tier' => 3,
        'power' => clienttranslate('Relancez tous les dés (bleus et vent).'),
        'power_code' => 'reroll_all',
    ],
    27 => [
        'name' => clienttranslate('Filibert'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Doublez l\'effet d\'un terrain (bonus ou malus).'),
        'power_code' => 'double_terrain',
    ],
    28 => [
        'name' => clienttranslate('Ragnard'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Transformez un dé noir en dé vert.'),
        'power_code' => 'black_to_green',
    ],
    29 => [
        'name' => clienttranslate('Ed'),
        'type' => CHAR_FER,
        'tier' => 2,
        'power' => clienttranslate('Gagnez +1 dé bleu permanent pour ce chapitre.'),
        'power_code' => 'extra_die_permanent',
    ],
    30 => [
        'name' => clienttranslate('Justin'),
        'type' => CHAR_FER,
        'tier' => 3,
        'power' => clienttranslate('Accumulez 1 dé bleu supplémentaire (max 3 accumulés).'),
        'power_code' => 'accumulate_dice',
    ],

    // ============ PACKS ============
    40 => [
        'name' => clienttranslate('Oshora'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Si vous êtes seul sur la tuile, +1 à tous vos dés.'),
        'power_code' => 'solo_bonus',
    ],
    41 => [
        'name' => clienttranslate('Saphira'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Ignorez 1 dé blanc si vous avez abandonné un hordier ce chapitre.'),
        'power_code' => 'abandon_ignore',
    ],
    42 => [
        'name' => clienttranslate('Wanda'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Ignorez 1 dé blanc du vent.'),
        'power_code' => 'ignore_one_wind',
    ],
    43 => [
        'name' => clienttranslate('Baramas'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Réduisez la force du vent de 1 (min 1).'),
        'power_code' => 'reduce_wind',
    ],
    44 => [
        'name' => clienttranslate('Ernest'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Le vent ne peut pas dépasser force 4 pour cette épreuve.'),
        'power_code' => 'cap_wind',
    ],
    45 => [
        'name' => clienttranslate('Galas'),
        'type' => CHAR_PACK,
        'tier' => 3,
        'power' => clienttranslate('Augmentez la force du vent de 1. Gagnez 2 points de moral.'),
        'power_code' => 'increase_wind_moral',
    ],
    46 => [
        'name' => clienttranslate('Rochelle'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Relancez 1 dé blanc du vent.'),
        'power_code' => 'reroll_wind',
    ],
    47 => [
        'name' => clienttranslate('Le Daron'),
        'type' => CHAR_PACK,
        'tier' => 3,
        'power' => clienttranslate('Si vous échouez, ne perdez pas de hordier (une fois par chapitre).'),
        'power_code' => 'save_hordier',
    ],
    48 => [
        'name' => clienttranslate('Vera'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Soignez 1 point de moral.'),
        'power_code' => 'heal_moral',
    ],
    49 => [
        'name' => clienttranslate('Bert'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Les dés verts comptent comme des dés bleus.'),
        'power_code' => 'green_as_blue',
    ],
    50 => [
        'name' => clienttranslate('Lethune'),
        'type' => CHAR_PACK,
        'tier' => 3,
        'power' => clienttranslate('Échangez 2 tuiles adjacentes.'),
        'power_code' => 'swap_tiles',
    ],
    51 => [
        'name' => clienttranslate('Josmina'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Les tuiles avec des dés noirs donnent +1 moral au lieu de -1.'),
        'power_code' => 'black_moral_flip',
    ],
    52 => [
        'name' => clienttranslate('Ashley'),
        'type' => CHAR_PACK,
        'tier' => 2,
        'power' => clienttranslate('Reposez tous vos hordiers. Perdez 1 point de moral par hordier reposé.'),
        'power_code' => 'mass_rest',
    ],

    // ============ TRAÎNES ============
    60 => [
        'name' => clienttranslate('Topilzin'),
        'type' => CHAR_TRAINE,
        'tier' => 1,
        'power' => clienttranslate('Abandonnez-moi. Ignorez tous les dés du vent pour cette épreuve.'),
        'power_code' => 'sacrifice_ignore_wind',
    ],
    61 => [
        'name' => clienttranslate('Osuros'),
        'type' => CHAR_TRAINE,
        'tier' => 1,
        'power' => clienttranslate('Abandonnez-moi. Réussissez automatiquement l\'épreuve en cours.'),
        'power_code' => 'sacrifice_auto_win',
    ],
    62 => [
        'name' => clienttranslate('Mère'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Gagnez 3 points de moral.'),
        'power_code' => 'sacrifice_moral_3',
    ],
    63 => [
        'name' => clienttranslate('Père'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Gagnez 2 points de moral et reposez la horde.'),
        'power_code' => 'sacrifice_moral_rest',
    ],
    64 => [
        'name' => clienttranslate('Yeng'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Ignorez les dés verts de cette tuile et des 2 prochaines.'),
        'power_code' => 'sacrifice_ignore_terrain_3',
    ],
    65 => [
        'name' => clienttranslate('Tala'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Remplacez la tuile actuelle par une tuile plaine.'),
        'power_code' => 'sacrifice_change_tile',
    ],
    66 => [
        'name' => clienttranslate('Zhalinka'),
        'type' => CHAR_TRAINE,
        'tier' => 3,
        'power' => clienttranslate('Abandonnez-moi. +1 à tous les dés par hordier déjà abandonné ce chapitre.'),
        'power_code' => 'sacrifice_bonus_abandoned',
    ],
    67 => [
        'name' => clienttranslate('Bellune'),
        'type' => CHAR_TRAINE,
        'tier' => 3,
        'power' => clienttranslate('Abandonnez-moi. Récupérez un hordier abandonné ce chapitre.'),
        'power_code' => 'sacrifice_recover',
    ],
    68 => [
        'name' => clienttranslate('Barakiel'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Transformez tous les dés noirs en dés violets.'),
        'power_code' => 'sacrifice_black_to_violet',
    ],
    69 => [
        'name' => clienttranslate('Charlize'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Doublez votre moral actuel (max 9).'),
        'power_code' => 'sacrifice_double_moral',
    ],
    70 => [
        'name' => clienttranslate('Abriyen'),
        'type' => CHAR_TRAINE,
        'tier' => 3,
        'power' => clienttranslate('Abandonnez-moi. Le prochain joueur perd 2 points de moral.'),
        'power_code' => 'sacrifice_hurt_next',
    ],
    71 => [
        'name' => clienttranslate('Comtesse'),
        'type' => CHAR_TRAINE,
        'tier' => 2,
        'power' => clienttranslate('Abandonnez-moi. Recrutez immédiatement 1 hordier de votre choix.'),
        'power_code' => 'sacrifice_recruit',
    ],
];
