<?php
/**
 * Windwalkers - Terrain Types
 * Values from land_cards.csv: White, Green, Black, Moral
 * Can rest on all tiles except Porte d'Hurle (effects vary by tile)
 */

$this->terrain_types = [
    'mountain' => [
        'name' => clienttranslate('Montagne'),
        'white_dice' => 3,
        'green_dice' => 3,
        'black_dice' => 0,
        'moral_effect' => 0,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'forest' => [
        'name' => clienttranslate('Forêt'),
        'white_dice' => 4,
        'green_dice' => 2,
        'black_dice' => 0,
        'moral_effect' => 0,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'steppe' => [
        'name' => clienttranslate('Steppe'),
        'white_dice' => 5,
        'green_dice' => 1,
        'black_dice' => 0,
        'moral_effect' => 0,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'plain' => [
        'name' => clienttranslate('Plaine'),
        'white_dice' => 5,
        'green_dice' => 1,
        'black_dice' => 0,
        'moral_effect' => 0,
        'can_rest' => true,
        'can_recruit' => false,
        'alias' => 'steppe',
    ],
    'hut' => [
        'name' => clienttranslate('Hutte'),
        'white_dice' => 6,
        'green_dice' => 0,
        'black_dice' => 0,
        'moral_effect' => 1,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'water' => [
        'name' => clienttranslate('Eau'),
        'white_dice' => 6,
        'green_dice' => 0,
        'black_dice' => 2,
        'moral_effect' => 0,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'desert' => [
        'name' => clienttranslate('Désert'),
        'white_dice' => 5,
        'green_dice' => 1,
        'black_dice' => 0,
        'moral_effect' => -2,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'swamp' => [
        'name' => clienttranslate('Marais'),
        'white_dice' => 4,
        'green_dice' => 2,
        'black_dice' => 1,
        'moral_effect' => -1,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'nordska' => [
        'name' => clienttranslate('Nordska'),
        'white_dice' => 4,
        'green_dice' => 3,
        'black_dice' => 3,
        'moral_effect' => -2,
        'can_rest' => true,
        'can_recruit' => false,
    ],
    'tourfontaine' => [
        'name' => clienttranslate('Tour Fontaine'),
        'white_dice' => 6,
        'green_dice' => 0,
        'black_dice' => 0,
        'moral_effect' => 0,
        'can_rest' => true,
        'can_recruit' => false,
        'special' => 'tourfontaine',
    ],
    'portedhurle' => [
        'name' => clienttranslate('Porte d\'Hurle'),
        'white_dice' => 0,
        'green_dice' => 0,
        'black_dice' => 6,
        'moral_effect' => 0,
        'can_rest' => false,
        'can_recruit' => false,
        'special' => 'portedhurle',
        'no_wind' => true,
    ],
];
